// Generates src/ort-version.ts and copies the onnxruntime-web .wasm/.mjs assets
// out of the resolved node_modules install into ./ort, next to main.js.
//
// Run BEFORE tsc/eslint/esbuild so the generated import exists on a clean
// checkout (build/lint/dev all depend on src/ort-version.ts, which is gitignored
// because it is a build artifact pinned to the installed dependency version).
import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import { createRequire } from "module";
import { fileURLToPath } from "url";

const require = createRequire(import.meta.url);
const here = dirname(fileURLToPath(import.meta.url));

// Resolve the onnxruntime-web package ROOT. Its package.json "exports" map blocks
// require.resolve("onnxruntime-web/package.json"), so resolve a file that IS
// exported (the wasm entry) and walk up to the dir that holds package.json.
// Falls back to the conventional node_modules location if resolution moves.
function resolveOrtDir() {
  try {
    let dir = dirname(require.resolve("onnxruntime-web"));
    for (let i = 0; i < 6; i++) {
      if (existsSync(join(dir, "package.json")) && existsSync(join(dir, "dist"))) {
        return dir;
      }
      dir = dirname(dir);
    }
  } catch {
    // fall through to the conventional path
  }
  const fallback = join(here, "node_modules", "onnxruntime-web");
  if (existsSync(join(fallback, "package.json"))) return fallback;
  throw new Error("Could not locate the onnxruntime-web package directory.");
}

const ortDir = resolveOrtDir();
const ortVersion = JSON.parse(
  readFileSync(join(ortDir, "package.json"), "utf8"),
).version;

// The JSEP build is what transformers v3 uses for BOTH the WebGPU and WASM
// backends. Ship the wasm-only glue too so a non-jsep path still resolves.
const ORT_WASM_FILES = [
  "ort-wasm-simd-threaded.jsep.wasm",
  "ort-wasm-simd-threaded.jsep.mjs",
  "ort-wasm-simd-threaded.wasm",
  "ort-wasm-simd-threaded.mjs",
];

export function genOrt() {
  // 1) Write the pinned version + CDN-fallback URL.
  const cdn = `https://cdn.jsdelivr.net/npm/onnxruntime-web@${ortVersion}/dist/`;
  const contents =
    "// AUTO-GENERATED by gen-ort.mjs — do not edit by hand.\n" +
    "// Pinned to the onnxruntime-web version @huggingface/transformers actually\n" +
    "// bundles, so the runtime CDN fallback can never drift from the shipped glue.\n" +
    `export const ORT_WEB_VERSION = ${JSON.stringify(ortVersion)};\n` +
    `export const ORT_WEB_CDN = ${JSON.stringify(cdn)};\n`;
  const target = join(here, "src", "ort-version.ts");
  let current = "";
  try {
    current = readFileSync(target, "utf8");
  } catch {
    current = "";
  }
  if (current !== contents) writeFileSync(target, contents);

  // 2) Copy the matching wasm assets next to main.js.
  const outDir = join(here, "ort");
  mkdirSync(outDir, { recursive: true });
  for (const f of ORT_WASM_FILES) {
    copyFileSync(join(ortDir, "dist", f), join(outDir, f));
  }

  return { ortVersion, cdn };
}

// Allow running directly: `node gen-ort.mjs`.
if (import.meta.url === `file://${process.argv[1]}`) {
  const { ortVersion: v } = genOrt();
  console.log(`Generated ort-version.ts and copied onnxruntime-web@${v} -> ort/`);
}
