// Generates src/ort-version.ts and copies the onnxruntime-web .wasm/.mjs assets
// out of the resolved node_modules install into ./ort, next to main.js.
//
// Run BEFORE tsc/eslint/esbuild so the generated import exists on a clean
// checkout (build/lint/dev all depend on src/ort-version.ts, which is gitignored
// because it is a build artifact pinned to the installed dependency version).
import { copyFileSync, existsSync, mkdirSync, readFileSync, rmSync, statSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import { createRequire } from "module";
import { fileURLToPath, pathToFileURL } from "url";

const require = createRequire(import.meta.url);
const here = dirname(fileURLToPath(import.meta.url));

// Resolve the onnxruntime-web package ROOT. Its package.json "exports" map blocks
// require.resolve("onnxruntime-web/package.json"), so resolve a file that IS
// exported (the wasm entry) and walk up to the dir that holds package.json.
// Falls back to the conventional node_modules location if resolution moves.
function resolveOrtDir() {
  try {
    let dir = dirname(require.resolve("onnxruntime-web"));
    for (let i = 0; i < 6; i++) {
      if (existsSync(join(dir, "package.json")) && existsSync(join(dir, "dist"))) {
        return dir;
      }
      dir = dirname(dir);
    }
  } catch {
    // fall through to the conventional path
  }
  const fallback = join(here, "node_modules", "onnxruntime-web");
  if (existsSync(join(fallback, "package.json"))) return fallback;
  throw new Error("Could not locate the onnxruntime-web package directory.");
}

const ortDir = resolveOrtDir();
// This version tracks the onnxruntime-web that @huggingface/transformers actually
// bundles — which is frequently a -dev snapshot (e.g. 1.22.0-dev.2025...). Do NOT
// pin it to a stable release independently: the self-hosted app:// primary .wasm
// and the JS glue transformers bundled must be the exact same build or ORT init
// fails ("create of undefined" / wasm-glue mismatch). The CDN fallback URL below
// is derived from this same version, so it can't drift either.
const ortVersion = JSON.parse(
  readFileSync(join(ortDir, "package.json"), "utf8"),
).version;

// transformers.js v4 loads the ASYNCIFY single-threaded web build for the WASM
// backend (its WebGPU path uses a native execution provider, not these files). Ship
// the asyncify pair the runtime points wasmPaths at, plus the plain pair as a
// fallback. Unlike the v3 jsep glue, the asyncify glue carries NO Node/worker_threads
// checks, so the old patchGlueForWeb step is gone — there is nothing to patch.
const ORT_WASM_FILES = [
  "ort-wasm-simd-threaded.asyncify.wasm",
  "ort-wasm-simd-threaded.asyncify.mjs",
  "ort-wasm-simd-threaded.wasm",
  "ort-wasm-simd-threaded.mjs",
];

export function genOrt() {
  // 1) Copy the matching wasm assets next to main.js. Clean first so a previous
  // build's (possibly differently-named) assets never linger in the folder.
  const outDir = join(here, "ort");
  rmSync(outDir, { recursive: true, force: true });
  mkdirSync(outDir, { recursive: true });
  for (const f of ORT_WASM_FILES) {
    const srcFile = join(ortDir, "dist", f);
    if (!existsSync(srcFile)) {
      throw new Error(
        `gen-ort: expected ORT asset missing: ${f} — the onnxruntime-web build ` +
          "layout changed; update ORT_WASM_FILES in gen-ort.mjs.",
      );
    }
    copyFileSync(srcFile, join(outDir, f));
  }

  // 2) Write the pinned version + CDN URL + the EXACT BYTE SIZES of the runtime
  // pair the bundled glue requires. The plugin validates any local or freshly
  // downloaded pair against these sizes before serving it to the worker — a
  // stateless integrity check that catches torn cache writes, stale files from
  // older installs after an onnxruntime-web bump, and CDN/proxy garbage, all of
  // which would otherwise fail ORT init with cryptic mixed-build errors.
  const cdn = `https://cdn.jsdelivr.net/npm/onnxruntime-web@${ortVersion}/dist/`;
  const glueBytes = statSync(join(outDir, "ort-wasm-simd-threaded.asyncify.mjs")).size;
  const wasmBytes = statSync(join(outDir, "ort-wasm-simd-threaded.asyncify.wasm")).size;
  const contents =
    "// AUTO-GENERATED by gen-ort.mjs — do not edit by hand.\n" +
    "// Pinned to the onnxruntime-web version @huggingface/transformers actually\n" +
    "// bundles, so the runtime download can never drift from the bundled glue.\n" +
    `export const ORT_WEB_VERSION = ${JSON.stringify(ortVersion)};\n` +
    `export const ORT_WEB_CDN = ${JSON.stringify(cdn)};\n` +
    `export const ORT_GLUE_BYTES = ${glueBytes};\n` +
    `export const ORT_WASM_BYTES = ${wasmBytes};\n`;
  const target = join(here, "src", "ort-version.ts");
  let current = "";
  try {
    current = readFileSync(target, "utf8");
  } catch {
    current = "";
  }
  if (current !== contents) writeFileSync(target, contents);

  return { ortVersion, cdn };
}

// Allow running directly: `node gen-ort.mjs`. Compare via pathToFileURL so the
// check survives paths containing spaces or other URL-encoded characters
// (import.meta.url is percent-encoded; a raw `file://${argv[1]}` template is not).
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const { ortVersion: v } = genOrt();
  console.log(`Generated ort-version.ts and copied onnxruntime-web@${v} -> ort/`);
}
